version: "3"
services:
  mongodb:
    image: mongo:4.1
    ports:
      - "27017:27017"
  webapp:
    build:
      context: .
      args:
        - JAR_FILE=target/demo*.jar
    ports:
      - "8091:8080"

